[workspace]
members = ["crates/cli", "crates/tui"]
resolver = "2"

[workspace.dependencies.fresnica-client]
git = "https://github.com/Fresnica/fresnica.git"
rev = "bad39935ce173b449c714150c24a63a1391ee4e7"

[workspace.dependencies.fresnica-sdk]
git = "https://github.com/Fresnica/fresnica.git"
rev = "bad39935ce173b449c714150c24a63a1391ee4e7"
